name: Manually Update Canvas

on:
  workflow_dispatch:
    inputs:
      canvas_id:
        description: 'Canvas ID'
        required: true
        type: string
      file_path:
        description: 'File path in the repository'
        required: true
        type: string

jobs:
  update_canvas:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read file
      id: read_file
      run: |
        echo "Reading file ${{ github.event.inputs.file_path }}"
        cat ${{ github.event.inputs.file_path }}
        echo "::set-output name=file_content::$(cat ${{ github.event.inputs.file_path }})"

    - name: Update Canvas
      env:
        TOKEN: ${{ secrets.SLACK_TOKEN }}
        CANVAS_ID: ${{ github.event.inputs.canvas_id }}
        CONTENTS: ${{ steps.read_file.outputs.file_content }}
      run: |
        response=$(curl --location 'https://slack.com/api/canvases.edit' \
          --header 'Content-Type: application/json' \
          --header "Authorization: Bearer $TOKEN" \
          --data '{
              "canvas_id": "$CANVAS_ID",
              "token": "$TOKEN",
              "changes": [
                {
                  "operation": "replace",
                  "document_content": {
                    "type": "markdown",
                    "markdown": "$CONTENTS"
                  }
                }
              ]
          }' --fail)
        
        status=$(echo $response | \
            python3 -c "import sys, json; print(json.load(sys.stdin)['ok'])")

        if [ "$status" = "True" ]; then
            echo "Canvas updated successfully"
        else
            echo "Failed to update canvas"
            exit 1
        fi